server:
  port: 8081
    
# Oracle #
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_02_2022_clientes?serverTimezone=GMT-6
    username: root
    password: sasa
    driverClassName: com.mysql.cj.jdbc.Driver

# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"